# Cherry Hand Pies {.unnumbered}

::: columns
::: {.column width="30%"}
**Preheat Oven:** 375&deg; F
:::

::: {.column width="5%"}
:::

::: {.column width="30%"}
**Prep Time:** 1hr 30min 
:::

::: {.column width="5%"}
:::

::: {.column width="30%"}
**Bake Time:** 20-25min
:::
:::

## Ingredients 

::: columns
::: {.column width="48%"}

**Pie Crust**

* 2 $\frac{1}{2}$ cups (150 grams) all-purpose flour

* 4 teaspoons granulated sugar (optional)

* 1 teaspoon salt

* 1 cup (115 grams) cold unsalted butter*, diced into $\frac{1}{4}$-inch cubes

* $\frac{1}{2}$ cup ice water

:::

::: {.column width="2%"}
:::

::: {.column width="48%"}

**Cherry Filling**

* $\frac{1}{2}$ cup (4oz/115g) sugar

* 2 tablespoons cornstarch

* 1 tablespoon lemon juice

* $\frac{1}{2}$ cup (4floz/115ml) water

* 2 cups (10oz/284g) cherries, pitted and halved

* 1 egg wash

* sugar to sprinkle on top

:::
:::

## Directions

1.  Prepare the pie crust: 

    a. Combine the dry ingredients (four, sugar, and salt) in a food processor.
    
    b. Cut the butter into the dry ingredients by briefly pulsing the butter and dry ingredients together 5 to 7 times until the butter is evenly dispersed into pea-sized (or smaller) bits.
    
    c. Transfer to a mixing bowl and quickly mix the water into the dough with a spatula. 
    
    d. Form a dough ball using your hands, and then flatten the ball into a $\frac{3}{4}$ inch thick disk. 
    
    e. Wrap and chill dough in the refrigerator for at least 1 hour or up to 3 days, until ready to roll out and use. 

2. Preheat the oven to 375 degrees. 

3. Make the filling: 

    a. In a saucepan over medium heat, combine sugar, cornstarch, lemon juice, and water.
    
    b. Let simmer for 2-3 minutes, until thickened.
    
    c. Remove from heat and stir in the cherries. 
    
    d. Set aside to cool.
  
4. Roll out pie crust and cut out 5 inch circles. (We trace bowls)

5. Spoon a small amount of cherry filling into the center of the cut pie crust, moisten the edge with some egg wash and fold over into a half-moon shape. Press down with your fingers or a fork to seal.

6. Place assembled pies on the baking sheets and refrigerate for 30 minutes.

7. When ready to bake, cut a few slits in the top crust of the pies, brush with the egg wash, and sprinkle sugar on top.

8. Bake for about 20-25 minutes, or until the crust is golden brown.

9. Store pies, loosely covered, at room temperature for up to 2 days. Refresh in a 300°F (150°C) oven for 10 minutes.

## Sources

[Homemade Pie Crust](https://www.gimmesomeoven.com/how-to-make-a-pie-crust-recipe/)

[Cherry Hand Pies from Scratch](https://www.biggerbolderbaking.com/cherry-hand-pies/)


